# 🐼 Python Pandas Cheat Sheet

In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["x","y","z"])

In [3]:
df.head() #we can look at the specific rows by using df.head(row number)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [9]:
df.tail(1)      #tail to look at the end of data

   A  B  C
2  7  8  9

In [21]:
df.columns     #to look at the headders of the dataset

Index(['A', 'B', 'C'], dtype='object')

In [22]:
df.index     #to view index of the list

Index(['x', 'y', 'z'], dtype='object')

In [23]:
df.index.tolist()     #to view the indexes in a list

['x', 'y', 'z']

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [26]:
df.describe()     #to find math values of the data like mean median mode etc...

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [30]:
df.nunique()     #to find no of unq values in each column

A    3
B    3
C    3
dtype: int64

In [33]:
df['A'].unique()

array([1, 4, 7])

In [36]:
df.shape

(3, 3)

In [39]:
df.size

9

## Practicing on Small Dataset
 coffee shop data from coffee.csv in datasets

In [2]:
coffee= pd.read_csv('coffee.csv')

In [3]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [8]:
results = pd.read_csv('results.csv')
bios = pd.read_csv('bios.csv')
olympics_data = pd.read_excel('olympics-data.xlsx', sheet_name="results")

 ## Accessing Data with Pandas

In [28]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [29]:
coffee.sample(10     #gives random 10 values

          Day Coffee Type  Units Sold
9      Friday       Latte          35
1      Monday       Latte          15
10   Saturday    Espresso          45
5   Wednesday       Latte          25
11   Saturday       Latte          35
3     Tuesday       Latte          20
6    Thursday    Espresso          40
0      Monday    Espresso          25
12     Sunday    Espresso          45
7    Thursday       Latte          30

In [32]:
coffee.head(10)     #acess top 10 elements

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [33]:
coffee.tail()     #accesing only last 5 values by default

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [35]:
coffee.tail(10)     #accesing last 10 rows of the data

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

### loc and iloc

In [115]:
coffee.loc[0]     #coffee.loc[row,column]to view specific columns and rows of data we use loc or iloc

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [42]:
coffee.loc[[0,1,4,5]]     #specific rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

In [47]:
coffee.loc[0:8]     #slicing is possible in loc accesing

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45

In [55]:
coffee.loc[0:8,["Day","Units Sold"]]     # you can use combination of rows and columns acccesing

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [58]:
coffee.iloc[:,[0,2]]      
#iloc is similar to loc but insted of using labels like day and units sold we use indexing in iloc

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

## Assigining Values

In [92]:
coffee.loc[1,'Units Sold']=10

In [94]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

### Using at and iat

In [97]:
coffee.at[0,"Units Sold"]      #at and iat can be used to access only that one single value

np.int64(25)

### Getting Columns

In [100]:
coffee.Day         #works with non spaced column names

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [102]:
coffee.Units Sold      #doesnt work with column nams with space

SyntaxError: invalid syntax (947029820.py, line 1)

In [106]:
coffee["Units Sold"]      #this is how you work with column names wih spaces

0     25
1     10
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

### Sort Values

In [109]:
coffee.sort_values(["Units Sold"],ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [112]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=False)      
#first it will sort by units sold and next it will again sort by lexographical/alphabeticall values look at the diff between previous and now sorting prev:10 8 12 6 4   but now the order is 8 10 12 6 9

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          10

### Iterate over dataframe with for loop

In [114]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("Coffee Type of Row:", row["Coffee Type"])
    # not recommended to iterate in datasets it might loose performance

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
Coffee Type of Row: Espresso
1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object
Coffee Type of Row: Latte
2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object
Coffee Type of Row: Espresso
3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object
Coffee Type of Row: Latte
4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
Coffee Type of Row: Espresso
5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
Coffee Type of Row: Latte
6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
Coffee Type of Row: Espresso
7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
Coffee Type of Row: Latte
8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
Coffee Type of Row: Espresso
9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
Coffee Type of Row: Latte
10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
Coffee Type of Row: Espresso
11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
Coffee Type of Row: Latte
12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
Coffee Type of Row: Espresso
13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
Coffee Type of Row: Latte

## Adding and Removing Columns

In [5]:
 coffee["Price"]=4.99

In [7]:
coffee

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [10]:
coffee['new_price']=np.where(coffee['Coffee Type']=='Espresso',3.99,5.99)

In [11]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [10]:
coffee.drop(columns=["Price"])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [11]:
coffee

          Day Coffee Type  Units Sold  Price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [12]:
coffee.drop(columns=["Price"],inplace=True)

In [13]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [18]:
coffee_new=coffee       
#here you are not creating a new dataset just that coffee_new is pointing towards coffee 
#so any change in coffee_new is also reflected in coffee 
#to fix that to create a new dataset to actually copy a dataset to a new variable u use .copy()

In [19]:
coffee_new["price"]=6.99

In [20]:
coffee_new

          Day Coffee Type  Units Sold  new_price  price
0      Monday    Espresso          25       3.99   6.99
1      Monday       Latte          15       5.99   6.99
2     Tuesday    Espresso          30       3.99   6.99
3     Tuesday       Latte          20       5.99   6.99
4   Wednesday    Espresso          35       3.99   6.99
5   Wednesday       Latte          25       5.99   6.99
6    Thursday    Espresso          40       3.99   6.99
7    Thursday       Latte          30       5.99   6.99
8      Friday    Espresso          45       3.99   6.99
9      Friday       Latte          35       5.99   6.99
10   Saturday    Espresso          45       3.99   6.99
11   Saturday       Latte          35       5.99   6.99
12     Sunday    Espresso          45       3.99   6.99
13     Sunday       Latte          35       5.99   6.99

In [21]:
coffee

          Day Coffee Type  Units Sold  new_price  price
0      Monday    Espresso          25       3.99   6.99
1      Monday       Latte          15       5.99   6.99
2     Tuesday    Espresso          30       3.99   6.99
3     Tuesday       Latte          20       5.99   6.99
4   Wednesday    Espresso          35       3.99   6.99
5   Wednesday       Latte          25       5.99   6.99
6    Thursday    Espresso          40       3.99   6.99
7    Thursday       Latte          30       5.99   6.99
8      Friday    Espresso          45       3.99   6.99
9      Friday       Latte          35       5.99   6.99
10   Saturday    Espresso          45       3.99   6.99
11   Saturday       Latte          35       5.99   6.99
12     Sunday    Espresso          45       3.99   6.99
13     Sunday       Latte          35       5.99   6.99

In [23]:
coffee_new.drop(columns="price",inplace=True)

In [24]:
coffee_new

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [25]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [27]:
coffee_dup=coffee.copy()

In [29]:
coffee_dup["Price"]=7.99

In [30]:
coffee_dup

          Day Coffee Type  Units Sold  new_price  Price
0      Monday    Espresso          25       3.99   7.99
1      Monday       Latte          15       5.99   7.99
2     Tuesday    Espresso          30       3.99   7.99
3     Tuesday       Latte          20       5.99   7.99
4   Wednesday    Espresso          35       3.99   7.99
5   Wednesday       Latte          25       5.99   7.99
6    Thursday    Espresso          40       3.99   7.99
7    Thursday       Latte          30       5.99   7.99
8      Friday    Espresso          45       3.99   7.99
9      Friday       Latte          35       5.99   7.99
10   Saturday    Espresso          45       3.99   7.99
11   Saturday       Latte          35       5.99   7.99
12     Sunday    Espresso          45       3.99   7.99
13     Sunday       Latte          35       5.99   7.99

In [31]:
coffee
#no effect on coffee dataset bcoz of coffee_dup

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [12]:
coffee["Revenue"]=coffee["Units Sold"]*coffee["new_price"]

In [13]:
coffee

          Day Coffee Type  Units Sold  new_price  Revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [36]:
coffee.rename(columns={"new_price":"Price"})

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [37]:
coffee
#no Price in place of new_price because we need to do inplace=True for it
#or else make it- coffee=coffee.rename(columns={"new_price":"Price"})

          Day Coffee Type  Units Sold  new_price  Revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [38]:
coffee.rename(columns={"new_price":"Price"},inplace=True)

In [6]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## Handling Null Values

In [8]:
coffee.loc[[0,1],"Units Sold"]=np.nan

In [9]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso         NaN
1      Monday       Latte         NaN
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [11]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   12 non-null     float64
dtypes: float64(1), object(2)
memory usage: 468.0+ bytes

In [12]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
dtype: int64

In [25]:
coffee.fillna(1000000)
#directly replace it with a value

          Day Coffee Type  Units Sold
0      Monday    Espresso   1000000.0
1      Monday       Latte   1000000.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [20]:
coffee.loc[[0,1],"Units Sold"]=np.nan

In [21]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso         NaN
1      Monday       Latte         NaN
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [31]:
coffee=coffee.fillna(coffee["Units Sold"].mean())
#fill it with mean of the column

In [32]:
coffee.loc[[2,3],"Units Sold"]=np.nan

In [33]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        37.0
1      Monday       Latte        37.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [35]:
coffee["Units Sold"]=coffee["Units Sold"].interpolate()
#interpolate relates it with neighbouring patterns

In [36]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso   37.000000
1      Monday       Latte   37.000000
2     Tuesday    Espresso   36.333333
3     Tuesday       Latte   35.666667
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [38]:
coffee.loc[[2,3],"Units Sold"]=np.nan

In [39]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        37.0
1      Monday       Latte        37.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [42]:
coffee.dropna()
#drop data with null values

          Day Coffee Type  Units Sold
0      Monday    Espresso        37.0
1      Monday       Latte        37.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [48]:
coffee.loc[[2,3],"Units Sold"]=np.nan

In [49]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        37.0
1      Monday       Latte        37.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [50]:
coffee[coffee["Units Sold"].isna()]

       Day Coffee Type  Units Sold
2  Tuesday    Espresso         NaN
3  Tuesday       Latte         NaN

In [4]:
coffee[coffee["Units Sold"].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## Aggregating Data

In [11]:
coffee.groupby(['Coffee Type'])["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [12]:
coffee.groupby(['Coffee Type'])["Units Sold"].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [17]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [4]:
pivot=coffee.pivot(columns="Coffee Type",index="Day",values="Units Sold")

In [5]:
pivot

Coffee Type  Espresso  Latte
Day
Friday             45     35
Monday             25     15
Saturday           45     35
Sunday             45     35
Thursday           40     30
Tuesday            30     20
Wednesday          35     25

## Advanced Functionality

In [6]:
# .shift()  .rank()  .rolling()  .cumsum()

In [14]:
coffee

          Day Coffee Type  Units Sold  new_price  Revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [16]:
coffee["yesterday_revenue"]=coffee["Revenue"].shift(2)

In [17]:
coffee

          Day Coffee Type  Units Sold  new_price  Revenue  yesterday_revenue
0      Monday    Espresso          25       3.99    99.75                NaN
1      Monday       Latte          15       5.99    89.85                NaN
2     Tuesday    Espresso          30       3.99   119.70              99.75
3     Tuesday       Latte          20       5.99   119.80              89.85
4   Wednesday    Espresso          35       3.99   139.65             119.70
5   Wednesday       Latte          25       5.99   149.75             119.80
6    Thursday    Espresso          40       3.99   159.60             139.65
7    Thursday       Latte          30       5.99   179.70             149.75
8      Friday    Espresso          45       3.99   179.55             159.60
9      Friday       Latte          35       5.99   209.65             179.70
10   Saturday    Espresso          45       3.99   179.55             179.55
11   Saturday       Latte          35       5.99   209.65             209.65
12     Sunday    Espresso          45       3.99   179.55             179.55
13     Sunday       Latte          35       5.99   209.65             209.65

In [28]:
coffee["pct_change"]=coffee['Revenue']/coffee["yesterday_revenue"]*100

In [30]:
coffee

,Day,Coffee Type,Units Sold,new_price,Revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000
9,Friday,Latte,35,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000

In [32]:
coffee["cumulative_revenue"]=coffee['Revenue'].cumsum()

In [33]:
coffee

,Day,Coffee Type,Units Sold,new_price,Revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2225.40

In [48]:
latte=coffee[coffee['Coffee Type']=='Latte'].copy()

In [49]:
latte

,Day,Coffee Type,Units Sold,new_price,Revenue,yesterday_revenue,pct_change,cumulative_revenue
1,Monday,Latte,15,5.99,89.85,NaN,NaN,189.6
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,429.1
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,718.5
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1057.8
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1447.0
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,1836.2
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2225.4

In [51]:
latte['3day']=latte['Units Sold'].rolling(3).sum()

In [52]:
latte

,Day,Coffee Type,Units Sold,new_price,Revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,15,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,718.5,60.0
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1057.8,75.0
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1447.0,90.0
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,1836.2,100.0
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2225.4,105.0